version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t fc-bot:latest .
      - docker tag fc-bot:latest 941681414890.dkr.ecr.us-east-1.amazonaws.com/fc-bot:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 941681414890.dkr.ecr.us-east-1.amazonaws.com/fc-bot:latest