version: 2
jobs:
  build:
     docker:
      - image: circleci/node:7.10
     working_directory: ~/repo
     steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
  deploy:
     machine:
        enabled: true
     steps:
      - add_ssh_keys:
          fingerprints:
            - "fa:6f:18:25:ec:75:a2:27:45:18:fd:d2:bc:01:01:ea"
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export CLIENT_ID="$CLIENT_ID"' >> $BASH_ENV
            echo 'export CLIENT_SECRET="$CLIENT_SECRET"' >> $BASH_ENV
            echo 'export PORT="7337"' >> $BASH_ENV

      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "export CLIENT_ID=\"$CLIENT_ID\" && export CLIENT_SECRET=\"$CLIENT_SECRET\" && export PORT=\"$PORT\" && env && cd flexibot && forever stopall && git pull && forever -o logs/output.log -e logs/error.log start index.js" 

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
