version: 2
jobs:
  build:
     docker:
      - image: circleci/node:7.10
     working_directory: ~/repo
     steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
  deploy:
     machine:
        enabled: true
     steps:
      - add_ssh_keys:
          fingerprints:
            - "04:fb:3c:55:fc:c6:06:3c:09:91:3c:d0:fc:42:c3:a3"
      - run:
          name: Setup Environment Variables
          command: |
            echo 'export CLIENT_ID="$CLIENT_ID"' >> $BASH_ENV
            echo 'export CLIENT_SECRET="$CLIENT_SECRET"' >> $BASH_ENV
            echo 'export PORT="7337"' >> $BASH_ENV

      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "source ~/.bashrc && cd flexibot && forever stopall && git pull && forever start index.js"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
